---
- name: install shell packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - bash
    - bash-completion
    - screen
- name: install utility packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - ansible
    - apg
    - bar
    - dos2unix
    - grc
    - htop
    - hwinfo
    - iotop
    - keepassx
    - less
    - lsof
    - mc
    - mlocate
    - mtr
    - ncdu
    - p7zip
    - p7zip-full
    - pigz
    - psmisc
    - rfkill
    - rlwrap
    - rsync
    - time
    - vpnc
    - whois
    - zip
- name: install X packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - awesome
    - awesome-extra
    - lightdm
    - notification-daemon
    - gnome-terminal
- name: install debian-dev packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - debhelper
    - devscripts
    - dh-make
- name: install dictionary packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - aspell-en
    - aspell-pl
    - hunspell-en-us
    - myspell-pl
- name: install font packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - fonts-liberation
    - ttf-liberation
    - ttf-mscorefonts-installer
- name: install main packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - alsa-utils
    - anacron
    - apache2
    - apache2-mpm-itk
    - cups-client
    - etckeeper
    - evince
    - git
    - git-svn
    - iptables
    - keychain
    - network-manager
    - network-manager-gnome
    - ntp
    - ntp
    - openssh-server
    - openvpn
    - pavucontrol
    - pm-utils
    - preload
    - pulseaudio
    - subversion
    - sudo
    - tig
    - vim
    - vim-gtk
    - wine
    - xscreensaver
- name: install multimedia packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - acoustid-fingerprinter
    - audacity
    - cmus
    - easytag
    - faad
    - gimp
    - imagemagick
    - lame
    - libav-tools
    - mypaint
    - vlc
- name: install office packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - abook
    - biber
    - chromium
    - gnuplot
    - graphviz
    - hamster-applet
    - libreoffice
    - links
    - mcabber
    - mutt
    - mutt-patched
    - texlive
    - texlive-bibtex-extra
    - texlive-fonts-extra
    - texlive-lang-polish
    - texlive-latex-extra
- name: install programming packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - build-essential
    - ipython
    - java-package
    - libsqlite3-dev
    - libvirt-bin
    - maven
    - nodejs
    - openjdk-7-jdk
    - poedit
    - python
    - python-dev
    - python-pip
    - python-sphinx
    - python3
    - python3-dev
    - ruby
    - ruby-dev
    - virtualenv
- name: install screencasting packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - byzanz
    - key-mon
    - vokoscreen
